stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: awcloud/heaterbilling:${CICD_EXECUTION_SEQUENCE}
  env:
    PLUGIN_DEBUG: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment-dev.yaml
  - applyYamlConfig:
      path: ./deploy/deployment-stag.yaml
  - applyYamlConfig:
      path: ./deploy/deployment-prod.yaml
timeout: 60
notification: {}
