apiVersion: v1
kind: Service
metadata:
  name: heaterbilling
  namespace: prod
spec:
  selector:
    app: heaterbilling
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heaterbilling
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heaterbilling
  template:
    metadata:
      labels:
        app: heaterbilling
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeName: app-node-1
      containers:
        - name: heaterbilling
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: heaterbilling-config-vol
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: heaterbilling-config-vol
          configMap:
            name: frontend-conf-stag


