apiVersion: v1
kind: Service
metadata:
  name: heaterbilling
  namespace: dev
spec:
  selector:
    app: heaterbilling
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heaterbilling
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heaterbilling
  template:
    metadata:
      labels:
        app: heaterbilling
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeName: app-node-1
      containers:
        - name: heaterbilling
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
